spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/flux_db
spring.datasource.username=flux
spring.datasource.password=Dinossauro#3110

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
